spring:
    datasource:
        url: jdbc:mysql://localhost:3306/user_details
        username: root
        password:
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
            format_sql: true  # Move format_sql under hibernate
        show-sql: false
        database: mysql

application:
    security:
        jwt:
            secret-key: 529424ba8964aa3c4de609cf5b23f29a0741602186e31fdbd6605252faeef089
            expiration: 86400000
            refresh-token:
                expiration: 604800000
